### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by KajaKozuchBCC** [bcc-code/bcc-design#252] opened 2023-09-28 07:47 UTC
![Image](https://github.com/bcc-code/bcc-design/assets/115977403/9859df82-5aab-4cfc-a6d8-341b382af725)
![Image](https://github.com/bcc-code/bcc-design/assets/115977403/91a689be-3366-4967-b149-0dac718aa1ae)
![Image](https://github.com/bcc-code/bcc-design/assets/115977403/3fe84702-9f94-4f58-8958-808b7b77d058)

Acceptance criteria: 

- [ ] add variants have to be implemented (Demand structure: 
Accordions:
- Ready only
- Brand
- Interactive)

- [ ] interactive accordion - only header needed

**Comment by laurensgroeneveld** [comment] 2023-09-28 08:15
This seems to be a duplicate of #156, if that's the case let's close one and keep the other. I added some more technical acceptance criteria in the other ticket, and a link to Figma.

**Comment by KajaKozuchBCC** [comment] 2023-09-28 08:24
ok, thanks - let's close it then

**Closed as not planned** 2023-09-28 08:29 UTC
