### ISSUE TITLE
Accorditions

### ISSUE THREAD

**Issue by Timvanderlaan** [bcc-code/bcc-design#220] opened 2023-09-16 13:51 UTC
## User Story

As a ..., I want to ... so that ...

## Description

...

## Acceptance Criteria:

https://www.figma.com/file/6GvZltnPMH3yynzf7287Iu/BCC-Components---Master?type=design&node-id=347-3437&mode=design

**Comment by laurensgroeneveld** [comment] 2023-09-19 11:57
Duplicate of #156

**Closed as not planned by laurensgroeneveld** 2023-09-19 11:57 UTC
